version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - NAME_DB=${NAME_DB}
      - USER_DB=${USER_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
      - DB_HOST=db

volumes:
  postgres_data: